### ISSUE TITLE
Reminder improvements when updating an issue

### ISSUE THREAD

**Issue by noggan** [interactive-solutions/officebot#5]
Currently the bot does not consider the state an issue is updated to, which means a "time spent" reminder is sent every time an issue is updated to a new state.

This means that updating an issue to `Duplicate` / `Obsolete` / `To be discussed` causes a reminder to be sent to the user when no actual time have been spent working on the issue.

**Comment by jarnell** [comment]
Duplicate and obsolete are considered resolved tasks, which is what the state filter was set to before. I've now modified it to be:
`state:{released *},verified,{waiting for deploy *},{ready for test *}`
